apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-xxvgkrch
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-xxvgkrch 
  name: go-xxvgkrch
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-xxvgkrch
    weight: 100 
